### ISSUE TITLE
ledSetCount first cycle blinks count-1

### ISSUE THREAD

**Issue by f-peri** [alexmaurer-madis/statusled#1]
Hello,
Thank you for publishing this code - it is exactly what I was looking for. I am by no means an expert, nor do I presume to critique your code, but I have found that when using ledSetCount, the first time the sequence is run, only count-1 blinks occur. For example:

```
#include <statusled.h>

StatusLed sl = StatusLed();

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  
  uint32_t currentMillis=millis();

  sl.ledSetCount(3, 0.1, 0.4, 1);

  if(sl.process(currentMillis)) {           // Calling process will return true if the state of the LED has changed
    digitalWrite(LED_BUILTIN, sl.state);    // Update output (use !sl.state if you must invert the output)
  }
}

``` 
After reset, only 2 blinks and after the 1 sec pause, then 3 blinks thereafter.

If I am incorrectly calling the function, please advise.

Thanks.

**Comment by alexmaurer-madis** [comment]
@f-peri Thank you for opening this issue !

The library has been corrected according to your observations.

This has been committed to release [v1.0.5](https://github.com/alexmaurer-madis/statusled/releases/tag/v1.0.5) and the package has been pushed to [PlatformIO](https://registry.platformio.org/libraries/alexmaurer-madis/statusled)

It will also be available into [Arduino Library Manager](https://www.arduinolibraries.info/libraries/statusled)

**Comment by f-peri** [comment]
Thank you for making this update. I did try an experiment, changing line 162 to:

_currentcount = count + 1;

And it seemed to fix the issue for my needs. Of course, I did no regression, nor exhaustive testing so I cannot verify it will always work. I certainly do not mean to suggest your fix is insufficient.
